name: CI
on:
  push:
    branches:
      - main
      - r[1-9]
  pull_request:
    branches:
      - main
      - r[1-9]
jobs:
  build-and-push-ai-anomaly-detection:
    name: Build and push ai-anomaly-detection
    uses: eu-nebulous/github-actions/.github/workflows/build-and-push-container-image.yml@main
    with:
      context: ai-anomaly-detection
      image-name: ai-anomaly-detection
    secrets: inherit
